apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airbyte
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-repo/deployments'
    targetRevision: HEAD
    path: airbyte
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: airbyte
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
